name: SmpTeleporter
version: 1.0
api-version: 1.14
main: dev.tycho.SmpTeleporter.SmpTeleporter
author: TychoVI
commands:
  TpIcon:
    description: Set your teleporter icon for in the teleporters list.
    usage: /TpIcon